# Generated by Django 4.2.2 on 2023-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_product_slug_alter_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
